insert into public.stratagems (
  slug,
  name,
  code,
  section,
  icon,
  is_active
)
values
('mg-43-machine-gun', 'MG-43 Machine Gun', '["down","left","down","up","right"]'::jsonb, 'Patriotic Administration Center', '120px-Machine_Gun_Stratagem_Icon.png', true),
('apw-1-anti-materiel-rifle', 'APW-1 Anti-Materiel Rifle', '["down","left","right","up","down"]'::jsonb, 'Patriotic Administration Center', '120px-Anti-Materiel_Rifle_Stratagem_Icon.png', true),
('m-105-stalwart', 'M-105 Stalwart', '["down","left","down","up","up","left"]'::jsonb, 'Patriotic Administration Center', '120px-Stalwart_Stratagem_Icon.png', true),
('eat-17-expendable-anti-tank', 'EAT-17 Expendable Anti-Tank', '["down","down","left","up","right"]'::jsonb, 'Patriotic Administration Center', '120px-Expendable_Anti-Tank_Stratagem_Icon.png', true),
('gr-8-recoilless-rifle', 'GR-8 Recoilless Rifle', '["down","left","right","right","left"]'::jsonb, 'Patriotic Administration Center', '120px-Recoilless_Rifle_Stratagem_Icon.png', true),
('flam-40-flamethrower', 'FLAM-40 Flamethrower', '["down","left","up","down","up"]'::jsonb, 'Patriotic Administration Center', '120px-Flamethrower_Stratagem_Icon.png', true),
('ac-8-autocannon', 'AC-8 Autocannon', '["down","left","down","up","up","right"]'::jsonb, 'Patriotic Administration Center', '120px-Autocannon_Stratagem_Icon.png', true),
('mg-206-heavy-machine-gun', 'MG-206 Heavy Machine Gun', '["down","left","up","down","down"]'::jsonb, 'Patriotic Administration Center', '120px-Heavy_Machine_Gun_Stratagem_Icon.png', true),
('rl-77-airburst-rocket-launcher', 'RL-77 Airburst Rocket Launcher', '["down","up","up","left","right"]'::jsonb, 'Patriotic Administration Center', '120px-RL-77_Airburst_Rocket_Launcher_Stratagem_Icon.png', true),
('mls-4x-commando', 'MLS-4X Commando', '["down","left","up","down","right"]'::jsonb, 'Patriotic Administration Center', '120px-Commando_Stratagem_Icon.png', true),
('rs-422-railgun', 'RS-422 Railgun', '["down","right","down","up","left","right"]'::jsonb, 'Patriotic Administration Center', '120px-Railgun_Stratagem_Icon.png', true),
('faf-14-spear', 'FAF-14 Spear', '["down","down","up","down","down"]'::jsonb, 'Patriotic Administration Center', '120px-Spear_Stratagem_Icon.png', true),
('sta-x3-w-a-s-p-launcher', 'StA-X3 W.A.S.P. Launcher', '["down","down","up","down","right"]'::jsonb, 'Patriotic Administration Center', '120px-StA-X3_W.png', true),
('orbital-gatling-barrage', 'Orbital Gatling Barrage', '["right","down","left","up","up"]'::jsonb, 'Orbital Cannons', '120px-Orbital_Gatling_Barrage_Stratagem_Icon.png', true),
('orbital-airburst-strike', 'Orbital Airburst Strike', '["right","right","right"]'::jsonb, 'Orbital Cannons', '120px-Orbital_Airburst_Strike_Stratagem_Icon.png', true),
('orbital-120mm-he-barrage', 'Orbital 120mm HE Barrage', '["right","right","down","left","right","down"]'::jsonb, 'Orbital Cannons', '120px-Orbital_120mm_HE_Barrage_Stratagem_Icon.png', true),
('orbital-380mm-he-barrage', 'Orbital 380mm HE Barrage', '["right","down","up","up","left","down","down"]'::jsonb, 'Orbital Cannons', '120px-Orbital_380mm_HE_Barrage_Stratagem_Icon.png', true),
('orbital-walking-barrage', 'Orbital Walking Barrage', '["right","down","right","down","right","down"]'::jsonb, 'Orbital Cannons', '120px-Orbital_Walking_Barrage_Stratagem_Icon.png', true),
('orbital-laser', 'Orbital Laser', '["right","down","up","right","down"]'::jsonb, 'Orbital Cannons', '120px-Orbital_Laser_Stratagem_Icon.png', true),
('orbital-napalm-barrage', 'Orbital Napalm Barrage', '["right","right","down","left","right","up"]'::jsonb, 'Orbital Cannons', '120px-Orbital_Napalm_Barrage_Stratagem_Icon.png', true),
('orbital-railcannon-strike', 'Orbital Railcannon Strike', '["right","up","down","down","right"]'::jsonb, 'Orbital Cannons', '120px-Orbital_Railcannon_Strike_Stratagem_Icon.png', true),
('eagle-strafing-run', 'Eagle Strafing Run', '["up","right","right"]'::jsonb, 'Hangar', '120px-Eagle_Strafing_Run_Stratagem_Icon.png', true),
('eagle-airstrike', 'Eagle Airstrike', '["up","right","down","right"]'::jsonb, 'Hangar', '120px-Eagle_Airstrike_Stratagem_Icon.png', true),
('eagle-cluster-bomb', 'Eagle Cluster Bomb', '["up","right","down","down","right"]'::jsonb, 'Hangar', '120px-Eagle_Cluster_Bomb_Stratagem_Icon.png', true),
('eagle-napalm-airstrike', 'Eagle Napalm Airstrike', '["up","right","down","up"]'::jsonb, 'Hangar', '120px-Eagle_Napalm_Airstrike_Stratagem_Icon.png', true),
('lift-850-jump-pack', 'LIFT-850 Jump Pack', '["down","up","up","down","up"]'::jsonb, 'Hangar', '120px-Jump_Pack_Stratagem_Icon.png', true),
('eagle-smoke-strike', 'Eagle Smoke Strike', '["up","right","up","down"]'::jsonb, 'Hangar', '120px-Eagle_Smoke_Strike_Stratagem_Icon.png', true),
('eagle-110mm-rocket-pods', 'Eagle 110mm Rocket Pods', '["up","right","up","left"]'::jsonb, 'Hangar', '120px-Eagle_110mm_Rocket_Pods_Stratagem_Icon.png', true),
('eagle-500kg-bomb', 'Eagle 500kg Bomb', '["up","right","down","down","down"]'::jsonb, 'Hangar', '120px-Eagle_500kg_Bomb_Stratagem_Icon.png', true),
('m-102-fast-recon-vehicle', 'M-102 Fast Recon Vehicle', '["left","down","right","down","right","down","up"]'::jsonb, 'Hangar', '120px-M-102_Fast_Recon_Vehicle_Stratagem_Icon.png', true),
('td-220-bastion-mk-xvi', 'TD-220 Bastion MK XVI', '["left","down","right","down","left","down","up","down","up"]'::jsonb, 'Hangar', 'Bastion_MK_XVI_Stratagem_Icon.svg', true),
('orbital-precision-strike', 'Orbital Precision Strike', '["right","right","up"]'::jsonb, 'Bridge', '120px-Orbital_Precision_Strike_Stratagem_Icon.png', true),
('orbital-gas-strike', 'Orbital Gas Strike', '["right","right","down","right"]'::jsonb, 'Bridge', '120px-Orbital_Gas_Strike_Stratagem_Icon.png', true),
('orbital-ems-strike', 'Orbital EMS Strike', '["right","right","left","down"]'::jsonb, 'Bridge', '120px-Orbital_EMS_Strike_Stratagem_Icon.png', true),
('orbital-smoke-strike', 'Orbital Smoke Strike', '["right","right","down","up"]'::jsonb, 'Bridge', '120px-Orbital_Smoke_Strike_Stratagem_Icon.png', true),
('e-mg-101-hmg-emplacement', 'E/MG-101 HMG Emplacement', '["down","up","left","right","right","left"]'::jsonb, 'Bridge', '120px-HMG_Emplacement_Stratagem_Icon.png', true),
('fx-12-shield-generator-relay', 'FX-12 Shield Generator Relay', '["down","down","left","right","left","right"]'::jsonb, 'Bridge', '120px-Shield_Generator_Relay_Stratagem_Icon.png', true),
('a-arc-3-tesla-tower', 'A/ARC-3 Tesla Tower', '["down","up","right","up","left","right"]'::jsonb, 'Bridge', '120px-Tesla_Tower_Stratagem_Icon.png', true),
('e-gl-21-grenadier-battlement', 'E/GL-21 Grenadier Battlement', '["down","right","down","left","right"]'::jsonb, 'Bridge', '120px-GL-21_Grenadier_Battlement_Stratagem_Icon.png', true),
('md-6-anti-personnel-minefield', 'MD-6 Anti-Personnel Minefield', '["down","left","up","right"]'::jsonb, 'Engineering Bay', '120px-Anti-Personnel_Minefield_Stratagem_Icon.png', true),
('b-1-supply-pack', 'B-1 Supply Pack', '["down","left","down","up","up","down"]'::jsonb, 'Engineering Bay', '120px-Supply_Pack_Stratagem_Icon.png', true),
('gl-21-grenade-launcher', 'GL-21 Grenade Launcher', '["down","left","up","left","down"]'::jsonb, 'Engineering Bay', '120px-Grenade_Launcher_Stratagem_Icon.png', true),
('las-98-laser-cannon', 'LAS-98 Laser Cannon', '["down","left","down","up","left"]'::jsonb, 'Engineering Bay', '120px-Laser_Cannon_Stratagem_Icon.png', true),
('md-i4-incendiary-mines', 'MD-I4 Incendiary Mines', '["down","left","left","down"]'::jsonb, 'Engineering Bay', '120px-Incendiary_Mines_Stratagem_Icon.png', true),
('ax-las-5-guard-dog-rover', 'AX/LAS-5 "Guard Dog" Rover', '["down","up","left","up","right","right"]'::jsonb, 'Engineering Bay', '120px-Guard_Dog_Rover_Stratagem_Icon.png', true),
('sh-20-ballistic-shield-backpack', 'SH-20 Ballistic Shield Backpack', '["down","left","down","down","up","left"]'::jsonb, 'Engineering Bay', '120px-Ballistic_Shield_Backpack_Stratagem_Icon.png', true),
('arc-3-arc-thrower', 'ARC-3 Arc Thrower', '["down","right","down","up","left","left"]'::jsonb, 'Engineering Bay', '120px-Arc_Thrower_Stratagem_Icon.png', true),
('md-17-anti-tank-mines', 'MD-17 Anti-Tank Mines', '["down","left","up","up"]'::jsonb, 'Engineering Bay', '120px-MD-17_Anti-Tank_Mines_Stratagem_Icon.png', true),
('las-99-quasar-cannon', 'LAS-99 Quasar Cannon', '["down","down","up","left","right"]'::jsonb, 'Engineering Bay', '120px-Quasar_Cannon_Stratagem_Icon.png', true),
('sh-32-shield-generator-pack', 'SH-32 Shield Generator Pack', '["down","up","left","right","left","right"]'::jsonb, 'Engineering Bay', '120px-Shield_Generator_Pack_Stratagem_Icon.png', true),
('md-8-gas-mines', 'MD-8 Gas Mines', '["down","left","left","right"]'::jsonb, 'Engineering Bay', '120px-Gas_Minefield_Stratagem_Icon.png', true),
('a-mg-43-machine-gun-sentry', 'A/MG-43 Machine Gun Sentry', '["down","up","right","right","up"]'::jsonb, 'Robotics Workshop', '120px-Machine_Gun_Sentry_Stratagem_Icon.png', true),
('a-g-16-gatling-sentry', 'A/G-16 Gatling Sentry', '["down","up","right","left"]'::jsonb, 'Robotics Workshop', '120px-Gatling_Sentry_Stratagem_Icon.png', true),
('a-m-12-mortar-sentry', 'A/M-12 Mortar Sentry', '["down","up","right","right","down"]'::jsonb, 'Robotics Workshop', '120px-Mortar_Sentry_Stratagem_Icon.png', true),
('ax-ar-23-guard-dog', 'AX/AR-23 "Guard Dog"', '["down","up","left","up","right","down"]'::jsonb, 'Robotics Workshop', '120px-Guard_Dog_Stratagem_Icon.png', true),
('a-ac-8-autocannon-sentry', 'A/AC-8 Autocannon Sentry', '["down","up","right","up","left","up"]'::jsonb, 'Robotics Workshop', '120px-Autocannon_Sentry_Stratagem_Icon.png', true),
('a-mls-4x-rocket-sentry', 'A/MLS-4X Rocket Sentry', '["down","up","right","right","left"]'::jsonb, 'Robotics Workshop', '120px-Rocket_Sentry_Stratagem_Icon.png', true),
('a-m-23-ems-mortar-sentry', 'A/M-23 EMS Mortar Sentry', '["down","up","right","down","right"]'::jsonb, 'Robotics Workshop', '120px-AM-23_EMS_Mortar_Sentry_Stratagem_Icon.png', true),
('exo-45-patriot-exosuit', 'EXO-45 Patriot Exosuit', '["left","down","right","up","left","down","down"]'::jsonb, 'Robotics Workshop', '120px-EXO-45_Patriot_Exosuit_Stratagem_Icon.png', true),
('exo-49-emancipator-exosuit', 'EXO-49 Emancipator Exosuit', '["left","down","right","up","left","down","up"]'::jsonb, 'Robotics Workshop', '120px-EXO-49_Emancipator_Exosuit_Stratagem_Icon.png', true),
('tx-41-sterilizer', 'TX-41 Sterilizer', '["down","left","up","down","left"]'::jsonb, 'Warbonds', '120px-Sterilizer_Stratagem_Icon.png', true),
('ax-tx-13-guard-dog-dog-breath', 'AX/TX-13 "Guard Dog" Dog Breath', '["down","up","left","up","right","up"]'::jsonb, 'Warbonds', '120px-Guard_Dog_Dog_Breath_Stratagem_Icon.png', true),
('sh-51-directional-shield', 'SH-51 Directional Shield', '["down","up","left","right","up","up"]'::jsonb, 'Warbonds', '120px-SH-51_Directional_Shield_Stratagem_Icon.png', true),
('e-at-12-anti-tank-emplacement', 'E/AT-12 Anti-Tank Emplacement', '["down","up","left","right","right","right"]'::jsonb, 'Warbonds', '120px-E_AT-12_Anti-Tank_Emplacement_Stratagem_Icon.png', true),
('a-flam-40-flame-sentry', 'A/FLAM-40 Flame Sentry', '["down","up","right","down","up","up"]'::jsonb, 'Warbonds', '120px-A_FLAM-40_Flame_Sentry_Stratagem_Icon.png', true),
('b-100-portable-hellbomb', 'B-100 Portable Hellbomb', '["down","right","up","up","up"]'::jsonb, 'Warbonds', '120px-Portable_Hellbomb_Stratagem_Icon.png', true),
('lift-860-hover-pack', 'LIFT-860 Hover Pack', '["down","up","up","down","left","right"]'::jsonb, 'Warbonds', 'Hover_Pack_Stratagem_Icon.png', true),
('cqc-1-one-true-flag', 'CQC-1 One True Flag', '["down","left","right","right","up"]'::jsonb, 'Warbonds', '120px-CQC-1_One_True_Flag_Stratagem_Icon.png', true),
('gl-52-de-escalator', 'GL-52 De-Escalator', '["down","right","up","left","right"]'::jsonb, 'Warbonds', 'GL-52_De-Escalator_Stratagem_Icon.png', true),
('ax-arc-3-guard-dog-k-9', 'AX/ARC-3 "Guard Dog" K-9', '["down","up","left","up","right","left"]'::jsonb, 'Warbonds', 'AX_ARC-3__Guard_Dog__K-9_Stratagem_Icon.png', true),
('plas-45-epoch', 'PLAS-45 Epoch', '["down","left","up","left","right"]'::jsonb, 'Warbonds', 'PLAS-45_Epoch_Stratagem_Icon.png', true),
('a-las-98-laser-sentry', 'A/LAS-98 Laser Sentry', '["down","up","right","down","up","right"]'::jsonb, 'Warbonds', '120px-A_LAS-98_Laser_Sentry_Stratagem_Icon.png', true),
('lift-182-warp-pack', 'LIFT-182 Warp Pack', '["down","left","right","down","left","right"]'::jsonb, 'Warbonds', 'LIFT-182_Warp_Pack_Stratagem_Icon.png', true),
('s-11-speargun', 'S-11 Speargun', '["down","right","down","left","up","right"]'::jsonb, 'Warbonds', '120px-S-11_Speargun_Stratagem_Icon.png', true),
('eat-700-expendable-napalm', 'EAT-700 Expendable Napalm', '["down","down","left","up","left"]'::jsonb, 'Warbonds', '120px-EAT-700_Expendable_Napalm_Stratagem_Icon.png', true),
('ms-11-solo-silo', 'MS-11 Solo Silo', '["down","up","right","down","down"]'::jsonb, 'Warbonds', '120px-MS-11_Stratagem_Icon.png', true),
('m-1000-maxigun', 'M-1000 Maxigun', '["down","left","right","down","up","up"]'::jsonb, 'Warbonds', 'M-1000_Maxigun_Stratagem_Icon.png', true),
('cqc-9-defoliation-tool', 'CQC-9 Defoliation Tool', '["down","left","right","right","down"]'::jsonb, 'Warbonds', 'CQC-9_Defoliation_Tool_Stratagem_Icon.png', true),
('ax-flam-75-guard-dog-hot-dog', 'AX/FLAM-75 "Guard Dog" Hot Dog', '["down","up","left","up","left","left"]'::jsonb, 'Warbonds', 'AX_FLAM-75_“Guard_Dog”_Hot_Dog_Stratagem_Icon.png', true),
('b-md-c4-pack', 'B/MD C4 Pack', '["down","right","up","up","right","up"]'::jsonb, 'Warbonds', '120px-B-MD_C4_Pack_Stratagem_Icon.png', true),
('a-gm-17-gas-mortar-sentry', 'A/GM-17 Gas Mortar Sentry', '["down","up","right","down","left"]'::jsonb, 'Warbonds', 'Gas_Mortar_Sentry_Stratagem_Icon.svg', true),
('b-flam-80-cremator', 'B/FLAM-80 Cremator', '["down","down","right","down","up","up"]'::jsonb, 'Warbonds', 'Cremator_Stratagem_Icon.svg', true),
('cqc-20-breaching-hammer', 'CQC-20 Breaching Hammer', '["down","left","right","left","up"]'::jsonb, 'Warbonds', 'Breaching_Hammer_Stratagem_Icon.svg', true),
('eat-411-leveller', 'EAT-411 Leveller', '["down","down","left","up","down"]'::jsonb, 'Warbonds', 'Leveller_Stratagem_Icon.svg', true),
('exo-51-lumberer-exosuit', 'EXO-51 Lumberer Exosuit', '["left","down","right","up","right","left","up"]'::jsonb, 'Warbonds', 'Lumberer_Exosuit_Stratagem_Icon.svg', true),
('exo-55-breakthrough-exosuit', 'EXO-55 Breakthrough Exosuit', '["left","down","right","left","right","down","up"]'::jsonb, 'Warbonds', 'Breakthrough_Exosuit_Stratagem_Icon.svg', true),
('gl-28-belt-fed-grenade-launcher', 'GL-28 Belt-Fed Grenade Launcher', '["down","left","up","left","up","up"]'::jsonb, 'Warbonds', 'Belt-Fed_Grenade_Launcher_Stratagem_Icon.svg', true),
('mgx-42-bullet-storm', 'MGX-42 Bullet Storm', '["down","left","down","right","up","left"]'::jsonb, 'Warbonds', 'Bullet_Storm_Stratagem_Icon.svg', true),
('reinforce', 'Reinforce', '["up","down","right","left","up"]'::jsonb, 'Mission Stratagems', '120px-Reinforce_Stratagem_Icon.png', true),
('sos-beacon', 'SoS Beacon', '["up","down","right","up"]'::jsonb, 'Mission Stratagems', '120px-SOS_Beacon_Stratagem_Icon.png', true),
('resupply', 'Resupply', '["down","down","up","right"]'::jsonb, 'Mission Stratagems', '120px-Resupply_Stratagem_Icon.png', true),
('eagle-rearm', 'Eagle Rearm', '["up","up","left","up","right"]'::jsonb, 'Mission Stratagems', '120px-Eagle_Rearm_Stratagem_Icon.png', true),
('call-in-super-destroyer', 'Call In Super Destroyer', '["up","up","down","down","left","right","left","right"]'::jsonb, 'Mission Stratagems', '120px-Call_In_Super_Destroyer_Stratagem_Icon.png', true),
('sssd-delivery', 'SSSD Delivery', '["down","down","down","up","up"]'::jsonb, 'Mission Stratagems', 'Start_Upload_Stratagem_Icon.png', true),
('prospecting-drill', 'Prospecting Drill', '["down","down","left","right","down","down"]'::jsonb, 'Mission Stratagems', '120px-Prospecting_Drill_Stratagem_Icon.png', true),
('super-earth-flag', 'Super Earth Flag', '["down","up","down","up"]'::jsonb, 'Mission Stratagems', '120px-Super_Earth_Flag_Stratagem_Icon.png', true),
('hellbomb', 'Hellbomb', '["down","up","left","down","up","right","down","up"]'::jsonb, 'Mission Stratagems', '120px-Hellbomb_Stratagem_Icon.png', true),
('upload-data', 'Upload Data', '["left","right","up","up","up"]'::jsonb, 'Mission Stratagems', 'Start_Upload_Stratagem_Icon.png', true),
('link-hellpods-to-destroyer', 'Link Hellpods to Destroyer', '["left","right","up","up","up"]'::jsonb, 'Mission Stratagems', 'Start_Upload_Stratagem_Icon.png', true),
('seismic-probe', 'Seismic Probe', '["up","up","left","right","down","down"]'::jsonb, 'Mission Stratagems', '120px-Seismic_Probe_Stratagem_Icon.png', true),
('orbital-illumination-flare', 'Orbital Illumination Flare', '["right","right","left","left"]'::jsonb, 'Mission Stratagems', '120px-Orbital_Illumination_Flare_Stratagem_Icon.png', true),
('seaf-artillery', 'SEAF Artillery', '["right","up","up","down"]'::jsonb, 'Mission Stratagems', '120px-SEAF_Artillery_Stratagem_Icon.png', true),
('dark-fluid-vessel', 'Dark Fluid Vessel', '["up","left","right","down","up","up"]'::jsonb, 'Mission Stratagems', '120px-Dark_Fluid_Vessel_Stratagem_Icon.png', true),
('tectonic-drill', 'Tectonic Drill', '["up","down","up","down","up","down"]'::jsonb, 'Mission Stratagems', '120px-Prospecting_Drill_Stratagem_Icon.png', true),
('hive-breaker-drill', 'Hive Breaker Drill', '["left","up","down","right","down","down"]'::jsonb, 'Mission Stratagems', '120px-Prospecting_Drill_Stratagem_Icon.png', true),
('cargo-container', 'Cargo Container', '["up","up","down","down","right","down"]'::jsonb, 'Mission Stratagems', 'Cargo_Container_Stratagem_Icon.png', true)
on conflict (slug)
do update set
  name = excluded.name,
  code = excluded.code,
  section = excluded.section,
  icon = excluded.icon,
  is_active = excluded.is_active;
